name: 04 working with 3rd party software
on: worflow_dispatch
jobs:
  node-20-release:
    runs-on: ubuntul-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - run: npm publish