name: 01 - building blocks

on:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello Wrold"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed steps
        run: |
          echo "This step will succeed"
  
      - name: Say echo-goodbye
        run: echo "goodbye world"
