name: 04-using-actions
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Printing Folders
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files:"
          ls -la
