name: 07-using expressions
run-name: 07-Using Expression | DEBUG - <'ON' if the debug is true, 'OFF' otherwise>
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print Start-up data"
        if: ${{ inputs.debug }} == "true"
        run: |
          echo "Triggered by ${{ github.event_name }}"
          echo "branch Name : ${{ github.ref_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}" 
          echo "Workflow: ${{ github.workflow }}"
          echo "Runner_OS: $RUNNER_OS  "
          echo "Runner OS runner.os:  ${{ runner.os}}"
      - name: "[debug] Print when triggered from main"
        if: ${{ inputs.debug }} ==  true &&  ${{ github.ref }} = 'refs/head/main'
        run: |
          echo "Triggered from main"
      - name: Greeting
        run: echo " Hello, World"


